version: "3.8"

services:
  # Frontend - React/Vite Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_YOUTUBE_API_URL=http://youtube-service:5001
    depends_on:
      - backend
      - youtube-service
    networks:
      - quiz-network
    restart: unless-stopped

  # Backend - Express.js (Gemini AI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - NODE_ENV=production
      - PORT=3001
    networks:
      - quiz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # YouTube Service - Python (Transcript API)
  youtube-service:
    build:
      context: ./youtube-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - PORT=5001
    networks:
      - quiz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  quiz-network:
    driver: bridge

volumes:
  node_modules:
